package com.company.item.dao.system;

import com.company.item.model.system.Goods;

public interface GoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int deleteByPrimaryKey(String goodsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insert(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insertSelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	Goods selectByPrimaryKey(String goodsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKeySelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKey(Goods record);
}