package com.company.item.dao.system;

import com.company.item.model.system.InHouserManagement;

public interface InHouserManagementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insert(InHouserManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insertSelective(InHouserManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	InHouserManagement selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKeySelective(InHouserManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKey(InHouserManagement record);
}