package com.company.item.dao.system;

import com.company.item.model.system.MaterialManagement;

public interface MaterialManagementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insert(MaterialManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insertSelective(MaterialManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	MaterialManagement selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKeySelective(MaterialManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKey(MaterialManagement record);
}