package com.company.item.dao.system;

import com.company.item.model.system.OutHouseManagement;

public interface OutHouseManagementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insert(OutHouseManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insertSelective(OutHouseManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	OutHouseManagement selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKeySelective(OutHouseManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table outhousemanagement
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKey(OutHouseManagement record);
}