package com.company.item.dao.system;

import com.company.item.model.system.ProControl;

public interface ProControlMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int deleteByPrimaryKey(String procode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insert(ProControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insertSelective(ProControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	ProControl selectByPrimaryKey(String procode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKeySelective(ProControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table procontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKey(ProControl record);
}