package com.company.item.dao.system;

import com.company.item.model.system.ProductManagement;

public interface ProductManagementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insert(ProductManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insertSelective(ProductManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	ProductManagement selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKeySelective(ProductManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_management
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKey(ProductManagement record);
}