package com.company.item.dao.system;

import com.company.item.model.system.StockControl;

public interface StockControlMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stockcontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int deleteByPrimaryKey(String goodcode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stockcontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insert(StockControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stockcontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insertSelective(StockControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stockcontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	StockControl selectByPrimaryKey(String goodcode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stockcontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKeySelective(StockControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stockcontrol
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKey(StockControl record);
}