package com.company.item.dao.system;

import com.company.item.model.system.Supplier;

public interface SupplierMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int deleteByPrimaryKey(String supplierId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insert(Supplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int insertSelective(Supplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	Supplier selectByPrimaryKey(String supplierId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKeySelective(Supplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	int updateByPrimaryKey(Supplier record);
}