package com.company.item.model.system;

import java.math.BigDecimal;
import java.util.Date;

public class Goods {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.goods_id
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String goodsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.goods_name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String goodsName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.goods_productdate
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private Date goodsProductdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.goods_qualitydate
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private Integer goodsQualitydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.goods_factory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String goodsFactory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.goods_saledate
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private Date goodsSaledate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.goods_id
	 * @return  the value of goods.goods_id
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getGoodsId() {
		return goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.goods_id
	 * @param goodsId  the value for goods.goods_id
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.goods_name
	 * @return  the value of goods.goods_name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getGoodsName() {
		return goodsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.goods_name
	 * @param goodsName  the value for goods.goods_name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.goods_productdate
	 * @return  the value of goods.goods_productdate
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public Date getGoodsProductdate() {
		return goodsProductdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.goods_productdate
	 * @param goodsProductdate  the value for goods.goods_productdate
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setGoodsProductdate(Date goodsProductdate) {
		this.goodsProductdate = goodsProductdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.goods_qualitydate
	 * @return  the value of goods.goods_qualitydate
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public Integer getGoodsQualitydate() {
		return goodsQualitydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.goods_qualitydate
	 * @param goodsQualitydate  the value for goods.goods_qualitydate
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setGoodsQualitydate(Integer goodsQualitydate) {
		this.goodsQualitydate = goodsQualitydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.goods_factory
	 * @return  the value of goods.goods_factory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getGoodsFactory() {
		return goodsFactory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.goods_factory
	 * @param goodsFactory  the value for goods.goods_factory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setGoodsFactory(String goodsFactory) {
		this.goodsFactory = goodsFactory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.price
	 * @return  the value of goods.price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.price
	 * @param price  the value for goods.price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.goods_saledate
	 * @return  the value of goods.goods_saledate
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public Date getGoodsSaledate() {
		return goodsSaledate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.goods_saledate
	 * @param goodsSaledate  the value for goods.goods_saledate
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setGoodsSaledate(Date goodsSaledate) {
		this.goodsSaledate = goodsSaledate;
	}
}