package com.company.item.model.system;

public class InHouserManagement {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inhousemanagement.code
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inhousemanagement.time
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inhousemanagement.name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inhousemanagement.inhousenumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String inhousenumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inhousemanagement.agent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String agent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inhousemanagement.lastnumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String lastnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inhousemanagement.nownumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String nownumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inhousemanagement.mark
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String mark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inhousemanagement.code
	 * @return  the value of inhousemanagement.code
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inhousemanagement.code
	 * @param code  the value for inhousemanagement.code
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inhousemanagement.time
	 * @return  the value of inhousemanagement.time
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inhousemanagement.time
	 * @param time  the value for inhousemanagement.time
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inhousemanagement.name
	 * @return  the value of inhousemanagement.name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inhousemanagement.name
	 * @param name  the value for inhousemanagement.name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inhousemanagement.inhousenumber
	 * @return  the value of inhousemanagement.inhousenumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getInhousenumber() {
		return inhousenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inhousemanagement.inhousenumber
	 * @param inhousenumber  the value for inhousemanagement.inhousenumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setInhousenumber(String inhousenumber) {
		this.inhousenumber = inhousenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inhousemanagement.agent
	 * @return  the value of inhousemanagement.agent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getAgent() {
		return agent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inhousemanagement.agent
	 * @param agent  the value for inhousemanagement.agent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setAgent(String agent) {
		this.agent = agent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inhousemanagement.lastnumber
	 * @return  the value of inhousemanagement.lastnumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getLastnumber() {
		return lastnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inhousemanagement.lastnumber
	 * @param lastnumber  the value for inhousemanagement.lastnumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setLastnumber(String lastnumber) {
		this.lastnumber = lastnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inhousemanagement.nownumber
	 * @return  the value of inhousemanagement.nownumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getNownumber() {
		return nownumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inhousemanagement.nownumber
	 * @param nownumber  the value for inhousemanagement.nownumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setNownumber(String nownumber) {
		this.nownumber = nownumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inhousemanagement.mark
	 * @return  the value of inhousemanagement.mark
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getMark() {
		return mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inhousemanagement.mark
	 * @param mark  the value for inhousemanagement.mark
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setMark(String mark) {
		this.mark = mark;
	}
}