package com.company.item.model.system;

public class MaterialManagement {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column material_management.ID
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column material_management.material_type
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String materialType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column material_management.material_price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String materialPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column material_management.material_inventory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String materialInventory;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column material_management.ID
	 * @return  the value of material_management.ID
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column material_management.ID
	 * @param id  the value for material_management.ID
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column material_management.material_type
	 * @return  the value of material_management.material_type
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getMaterialType() {
		return materialType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column material_management.material_type
	 * @param materialType  the value for material_management.material_type
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setMaterialType(String materialType) {
		this.materialType = materialType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column material_management.material_price
	 * @return  the value of material_management.material_price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getMaterialPrice() {
		return materialPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column material_management.material_price
	 * @param materialPrice  the value for material_management.material_price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setMaterialPrice(String materialPrice) {
		this.materialPrice = materialPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column material_management.material_inventory
	 * @return  the value of material_management.material_inventory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getMaterialInventory() {
		return materialInventory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column material_management.material_inventory
	 * @param materialInventory  the value for material_management.material_inventory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setMaterialInventory(String materialInventory) {
		this.materialInventory = materialInventory;
	}
}