package com.company.item.model.system;

public class OutHouseManagement {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outhousemanagement.code
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outhousemanagement.time
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outhousemanagement.name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outhousemanagement.outhousenumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String outhousenumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outhousemanagement.agent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String agent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outhousemanagement.lastnumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String lastnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outhousemanagement.nownumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String nownumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outhousemanagement.mark
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String mark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outhousemanagement.code
	 * @return  the value of outhousemanagement.code
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outhousemanagement.code
	 * @param code  the value for outhousemanagement.code
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outhousemanagement.time
	 * @return  the value of outhousemanagement.time
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outhousemanagement.time
	 * @param time  the value for outhousemanagement.time
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outhousemanagement.name
	 * @return  the value of outhousemanagement.name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outhousemanagement.name
	 * @param name  the value for outhousemanagement.name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outhousemanagement.outhousenumber
	 * @return  the value of outhousemanagement.outhousenumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getOuthousenumber() {
		return outhousenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outhousemanagement.outhousenumber
	 * @param outhousenumber  the value for outhousemanagement.outhousenumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setOuthousenumber(String outhousenumber) {
		this.outhousenumber = outhousenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outhousemanagement.agent
	 * @return  the value of outhousemanagement.agent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getAgent() {
		return agent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outhousemanagement.agent
	 * @param agent  the value for outhousemanagement.agent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setAgent(String agent) {
		this.agent = agent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outhousemanagement.lastnumber
	 * @return  the value of outhousemanagement.lastnumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getLastnumber() {
		return lastnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outhousemanagement.lastnumber
	 * @param lastnumber  the value for outhousemanagement.lastnumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setLastnumber(String lastnumber) {
		this.lastnumber = lastnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outhousemanagement.nownumber
	 * @return  the value of outhousemanagement.nownumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getNownumber() {
		return nownumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outhousemanagement.nownumber
	 * @param nownumber  the value for outhousemanagement.nownumber
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setNownumber(String nownumber) {
		this.nownumber = nownumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outhousemanagement.mark
	 * @return  the value of outhousemanagement.mark
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getMark() {
		return mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outhousemanagement.mark
	 * @param mark  the value for outhousemanagement.mark
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setMark(String mark) {
		this.mark = mark;
	}
}