package com.company.item.model.system;

public class ProControl {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procontrol.procode
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String procode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procontrol.proname
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String proname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procontrol.carryover
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String carryover;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procontrol.numberinhouse
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String numberinhouse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procontrol.numberoutage
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String numberoutage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procontrol.numbercurrent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String numbercurrent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procontrol.standardstock
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String standardstock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procontrol.overfolw
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String overfolw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procontrol.price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procontrol.cost
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String cost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column procontrol.totalinventory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String totalinventory;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procontrol.procode
	 * @return  the value of procontrol.procode
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getProcode() {
		return procode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procontrol.procode
	 * @param procode  the value for procontrol.procode
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setProcode(String procode) {
		this.procode = procode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procontrol.proname
	 * @return  the value of procontrol.proname
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getProname() {
		return proname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procontrol.proname
	 * @param proname  the value for procontrol.proname
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setProname(String proname) {
		this.proname = proname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procontrol.carryover
	 * @return  the value of procontrol.carryover
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getCarryover() {
		return carryover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procontrol.carryover
	 * @param carryover  the value for procontrol.carryover
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setCarryover(String carryover) {
		this.carryover = carryover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procontrol.numberinhouse
	 * @return  the value of procontrol.numberinhouse
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getNumberinhouse() {
		return numberinhouse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procontrol.numberinhouse
	 * @param numberinhouse  the value for procontrol.numberinhouse
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setNumberinhouse(String numberinhouse) {
		this.numberinhouse = numberinhouse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procontrol.numberoutage
	 * @return  the value of procontrol.numberoutage
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getNumberoutage() {
		return numberoutage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procontrol.numberoutage
	 * @param numberoutage  the value for procontrol.numberoutage
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setNumberoutage(String numberoutage) {
		this.numberoutage = numberoutage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procontrol.numbercurrent
	 * @return  the value of procontrol.numbercurrent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getNumbercurrent() {
		return numbercurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procontrol.numbercurrent
	 * @param numbercurrent  the value for procontrol.numbercurrent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setNumbercurrent(String numbercurrent) {
		this.numbercurrent = numbercurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procontrol.standardstock
	 * @return  the value of procontrol.standardstock
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getStandardstock() {
		return standardstock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procontrol.standardstock
	 * @param standardstock  the value for procontrol.standardstock
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setStandardstock(String standardstock) {
		this.standardstock = standardstock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procontrol.overfolw
	 * @return  the value of procontrol.overfolw
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getOverfolw() {
		return overfolw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procontrol.overfolw
	 * @param overfolw  the value for procontrol.overfolw
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setOverfolw(String overfolw) {
		this.overfolw = overfolw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procontrol.price
	 * @return  the value of procontrol.price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procontrol.price
	 * @param price  the value for procontrol.price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procontrol.cost
	 * @return  the value of procontrol.cost
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getCost() {
		return cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procontrol.cost
	 * @param cost  the value for procontrol.cost
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setCost(String cost) {
		this.cost = cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column procontrol.totalinventory
	 * @return  the value of procontrol.totalinventory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getTotalinventory() {
		return totalinventory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column procontrol.totalinventory
	 * @param totalinventory  the value for procontrol.totalinventory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setTotalinventory(String totalinventory) {
		this.totalinventory = totalinventory;
	}
}