package com.company.item.model.system;

public class ProductManagement {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_management.ID
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_management.product_types
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String productTypes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_management.product_price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String productPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_management.production_capacity
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String productionCapacity;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_management.ID
	 * @return  the value of product_management.ID
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_management.ID
	 * @param id  the value for product_management.ID
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_management.product_types
	 * @return  the value of product_management.product_types
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getProductTypes() {
		return productTypes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_management.product_types
	 * @param productTypes  the value for product_management.product_types
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setProductTypes(String productTypes) {
		this.productTypes = productTypes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_management.product_price
	 * @return  the value of product_management.product_price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getProductPrice() {
		return productPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_management.product_price
	 * @param productPrice  the value for product_management.product_price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setProductPrice(String productPrice) {
		this.productPrice = productPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_management.production_capacity
	 * @return  the value of product_management.production_capacity
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getProductionCapacity() {
		return productionCapacity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_management.production_capacity
	 * @param productionCapacity  the value for product_management.production_capacity
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setProductionCapacity(String productionCapacity) {
		this.productionCapacity = productionCapacity;
	}
}