package com.company.item.model.system;

public class Sale {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sale.sale_id
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String saleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sale.sale_name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String saleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sale.sale_status
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String saleStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sale.sale_factory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String saleFactory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sale.sale_time
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String saleTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sale.sale_amount
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String saleAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sale.sale_money
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String saleMoney;
	public String getSaleId() {
		return saleId;
	}
	public void setSaleId(String saleId) {
		this.saleId = saleId;
	}
	public String getSaleName() {
		return saleName;
	}
	public void setSaleName(String saleName) {
		this.saleName = saleName;
	}
	public String getSaleStatus() {
		return saleStatus;
	}
	public void setSaleStatus(String saleStatus) {
		this.saleStatus = saleStatus;
	}
	public String getSaleFactory() {
		return saleFactory;
	}
	public void setSaleFactory(String saleFactory) {
		this.saleFactory = saleFactory;
	}
	public String getSaleTime() {
		return saleTime;
	}
	public void setSaleTime(String saleTime) {
		this.saleTime = saleTime;
	}
	public String getSaleAmount() {
		return saleAmount;
	}
	public void setSaleAmount(String saleAmount) {
		this.saleAmount = saleAmount;
	}
	public String getSaleMoney() {
		return saleMoney;
	}
	public void setSaleMoney(String saleMoney) {
		this.saleMoney = saleMoney;
	}
	public Sale() {
		super();
	}


}