package com.company.item.model.system;

public class StockControl {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stockcontrol.goodcode
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String goodcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stockcontrol.goodname
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String goodname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stockcontrol.carryover
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String carryover;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stockcontrol.numberinhouse
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String numberinhouse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stockcontrol.numberoutage
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String numberoutage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stockcontrol.numbercurrent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String numbercurrent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stockcontrol.standardstock
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String standardstock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stockcontrol.overfolw
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String overfolw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stockcontrol.price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stockcontrol.cost
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String cost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stockcontrol.totalinventory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String totalinventory;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stockcontrol.goodcode
	 * @return  the value of stockcontrol.goodcode
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getGoodcode() {
		return goodcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stockcontrol.goodcode
	 * @param goodcode  the value for stockcontrol.goodcode
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setGoodcode(String goodcode) {
		this.goodcode = goodcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stockcontrol.goodname
	 * @return  the value of stockcontrol.goodname
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getGoodname() {
		return goodname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stockcontrol.goodname
	 * @param goodname  the value for stockcontrol.goodname
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setGoodname(String goodname) {
		this.goodname = goodname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stockcontrol.carryover
	 * @return  the value of stockcontrol.carryover
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getCarryover() {
		return carryover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stockcontrol.carryover
	 * @param carryover  the value for stockcontrol.carryover
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setCarryover(String carryover) {
		this.carryover = carryover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stockcontrol.numberinhouse
	 * @return  the value of stockcontrol.numberinhouse
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getNumberinhouse() {
		return numberinhouse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stockcontrol.numberinhouse
	 * @param numberinhouse  the value for stockcontrol.numberinhouse
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setNumberinhouse(String numberinhouse) {
		this.numberinhouse = numberinhouse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stockcontrol.numberoutage
	 * @return  the value of stockcontrol.numberoutage
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getNumberoutage() {
		return numberoutage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stockcontrol.numberoutage
	 * @param numberoutage  the value for stockcontrol.numberoutage
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setNumberoutage(String numberoutage) {
		this.numberoutage = numberoutage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stockcontrol.numbercurrent
	 * @return  the value of stockcontrol.numbercurrent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getNumbercurrent() {
		return numbercurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stockcontrol.numbercurrent
	 * @param numbercurrent  the value for stockcontrol.numbercurrent
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setNumbercurrent(String numbercurrent) {
		this.numbercurrent = numbercurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stockcontrol.standardstock
	 * @return  the value of stockcontrol.standardstock
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getStandardstock() {
		return standardstock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stockcontrol.standardstock
	 * @param standardstock  the value for stockcontrol.standardstock
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setStandardstock(String standardstock) {
		this.standardstock = standardstock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stockcontrol.overfolw
	 * @return  the value of stockcontrol.overfolw
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getOverfolw() {
		return overfolw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stockcontrol.overfolw
	 * @param overfolw  the value for stockcontrol.overfolw
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setOverfolw(String overfolw) {
		this.overfolw = overfolw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stockcontrol.price
	 * @return  the value of stockcontrol.price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stockcontrol.price
	 * @param price  the value for stockcontrol.price
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stockcontrol.cost
	 * @return  the value of stockcontrol.cost
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getCost() {
		return cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stockcontrol.cost
	 * @param cost  the value for stockcontrol.cost
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setCost(String cost) {
		this.cost = cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stockcontrol.totalinventory
	 * @return  the value of stockcontrol.totalinventory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getTotalinventory() {
		return totalinventory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stockcontrol.totalinventory
	 * @param totalinventory  the value for stockcontrol.totalinventory
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setTotalinventory(String totalinventory) {
		this.totalinventory = totalinventory;
	}
}