package com.company.item.model.system;

public class Supplier {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.supplier_id
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String supplierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.supplier_name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String supplierName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.supplier_address
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String supplierAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.supplier_phone
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	private String supplierPhone;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.supplier_id
	 * @return  the value of supplier.supplier_id
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.supplier_id
	 * @param supplierId  the value for supplier.supplier_id
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.supplier_name
	 * @return  the value of supplier.supplier_name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getSupplierName() {
		return supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.supplier_name
	 * @param supplierName  the value for supplier.supplier_name
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.supplier_address
	 * @return  the value of supplier.supplier_address
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getSupplierAddress() {
		return supplierAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.supplier_address
	 * @param supplierAddress  the value for supplier.supplier_address
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setSupplierAddress(String supplierAddress) {
		this.supplierAddress = supplierAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.supplier_phone
	 * @return  the value of supplier.supplier_phone
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public String getSupplierPhone() {
		return supplierPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.supplier_phone
	 * @param supplierPhone  the value for supplier.supplier_phone
	 * @mbggenerated  Wed Dec 27 20:55:59 CST 2017
	 */
	public void setSupplierPhone(String supplierPhone) {
		this.supplierPhone = supplierPhone;
	}
}